# Habilita o cache global para melhorar a performance do Yarn
enableGlobalCache: true

# Usa o padrão node-modules para o linkador de pacotes invés do Plug'n'Play (PnP)
nodeLinker: node-modules

# Sempre usa a versão específica do Yarn definida no projeto (3.8.5)
yarnPath: .yarn/releases/yarn-3.8.5.cjs