services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev